# Generated by Django 2.2.10 on 2021-03-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='it_background',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
