# Generated by Django 2.2.10 on 2021-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210325_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, null=True)),
            ],
            options={
                'db_table': 'data_sources',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
