# Generated by Django 2.2.10 on 2021-03-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210325_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='data_source_id',
            field=models.IntegerField(null=True),
        ),
    ]
