# Generated by Django 2.2.10 on 2021-03-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210326_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField()),
                ('file_name', models.CharField(max_length=255)),
                ('data_source_name', models.CharField(max_length=255)),
                ('execution_time_in_seconds', models.IntegerField()),
                ('number_of_records', models.IntegerField()),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
