# Generated by Django 2.2.10 on 2021-03-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210327_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='number_of_records',
            field=models.FloatField(null=True),
        ),
    ]
