# Generated by Django 2.2.10 on 2021-03-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210327_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='execution_time_in_seconds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='number_of_records',
            field=models.IntegerField(),
        ),
    ]
