# Generated by Django 2.2.10 on 2021-03-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210327_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='job_date',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
